apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - image: drupal:4.8-apache
        name: drupal
        ports:
        - containerPort: 80
          name: drupal
        volumeMounts:
        - name: drupal-storage
          mountPath: /var/www/html
      volumes:
      - name: drupal-storage
        emptyDir: {}
